import { sql } from 'drizzle-orm';
import { integer, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

/**
 * Domain schema for the core-entity ERD (ARCHITECTURE-SPINE.md):
 * LANDLORD -> UNIT -> LEASE <- TENANT, plus invitation tokens (CAP-6/CAP-7).
 * Every later story's schema additions (payments, refunds, autopay
 * mandates, lease documents) build on these tables.
 *
 * IDs: UUIDv7 (Consistency Conventions), generated by Postgres 18's native
 * `uuidv7()` -- sortable, avoids sequential enumeration.
 */

const uuidv7 = sql`uuidv7()`;

export const invitationStatus = pgEnum('invitation_status', ['pending', 'active']);
export const leaseStatus = pgEnum('lease_status', ['active', 'ended']);

export const landlords = pgTable('landlords', {
  id: uuid('id').primaryKey().default(uuidv7),
  /** Normalized (case-folded) email -- the allowlisted identity (CAP-7, AD-5). */
  email: text('email').notNull(),
  /** Normalized E.164 phone, if the landlord also uses phone+OTP. */
  phone: text('phone'),
  name: text('name').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  // Enforces "no path may create a second landlord account" at the data layer.
  uniqueIndex('landlords_email_unique').on(table.email),
]);

export const units = pgTable('units', {
  id: uuid('id').primaryKey().default(uuidv7),
  landlordId: uuid('landlord_id').notNull().references(() => landlords.id, { onDelete: 'cascade' }),
  label: text('label').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const tenants = pgTable('tenants', {
  id: uuid('id').primaryKey().default(uuidv7),
  landlordId: uuid('landlord_id').notNull().references(() => landlords.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  /** Normalized (case-folded) email on file -- used for future identity resolution (AD-5), not necessarily the login identifier. */
  email: text('email').notNull(),
  /** Normalized E.164 phone on file. */
  phone: text('phone').notNull(),
  invitationStatus: invitationStatus('invitation_status').notNull().default('pending'),
  /**
   * Better Auth `user.id` this tenant resolves to once activated
   * (Story 3 / CAP-6). Intentionally not a DB foreign key into
   * `auth_user` -- Better Auth owns that table's lifecycle and this story
   * does not modify it. Null until activation.
   */
  authUserId: text('auth_user_id'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('tenants_email_unique').on(table.email),
]);

export const leases = pgTable('leases', {
  id: uuid('id').primaryKey().default(uuidv7),
  unitId: uuid('unit_id').notNull().references(() => units.id, { onDelete: 'cascade' }),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  startDate: timestamp('start_date', { withTimezone: true }).notNull(),
  endDate: timestamp('end_date', { withTimezone: true }),
  /** Rent amount in paise (integer) -- avoids floating-point money bugs. */
  rentAmountPaise: integer('rent_amount_paise').notNull(),
  status: leaseStatus('status').notNull().default('active'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const invitationTokens = pgTable('invitation_tokens', {
  id: uuid('id').primaryKey().default(uuidv7),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  /** SHA-256 hex digest of the raw token -- the raw token is never persisted. */
  tokenHash: text('token_hash').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  usedAt: timestamp('used_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});
